# Generated by Django 5.1.2 on 2024-12-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0003_alter_experience_category_alter_experience_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Allow multiple bookings'),
        ),
        migrations.AddField(
            model_name='experience',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
