# Generated by Django 5.1.2 on 2024-12-20 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0004_experience_event_date_experience_is_public_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='event_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
